name: Build Windows Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r PCCompanion/requirements_cross_platform.txt
        pip install pyinstaller
    
    - name: Build Windows executable
      run: |
        cd PCCompanion
        pyinstaller --onefile --windowed --name=ArtRemoteServer-Windows --icon=../icon.ico art_remote_server_cross_platform.py
    
    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: ArtRemoteServer-Windows
        path: PCCompanion/dist/ArtRemoteServer-Windows.exe
